DROP TABLE timed_event_table;
DROP TABLE troop_table;
DROP TABLE resource_table;
DROP TABLE building_table;
DROP TABLE kingdom_table;
DROP TABLE user_table;
CREATE TABLE APPUSER (ID BIGSERIAL NOT NULL, USERNAME VARCHAR(50) NOT NULL, PASSWORD VARCHAR(100) NOT NULL, FIRSTNAME VARCHAR(50) NOT NULL, LASTNAME VARCHAR(50) NOT NULL, EMAIL VARCHAR(50) NOT NULL, ENABLED BOOLEAN NOT NULL, LASTPASSWORDRESETDATE DATE NOT NULL, POINTS INT NOT NULL, PRIMARY KEY(ID));
CREATE TABLE AUTHORITY (ID BIGSERIAL NOT NULL, NAME VARCHAR(50) NOT NULL, APPUSER_ID BIGINT REFERENCES APPUSER(ID), PRIMARY KEY (ID));
CREATE TABLE USER_AUTHORITY(USER_ID BIGINT REFERENCES APPUSER(ID), AUTHORITY_ID BIGINT REFERENCES AUTHORITY(ID), PRIMARY KEY (USER_ID, AUTHORITY_ID));
CREATE TABLE kingdom_table(kingdom_id BIGSERIAL NOT NULL, kingdom_name VARCHAR(255), ID BIGINT REFERENCES APPUSER(ID), PRIMARY KEY (kingdom_id));
CREATE TABLE building_table(building_id BIGSERIAL NOT NULL, kingdom_id BIGINT REFERENCES kingdom_table(kingdom_id), building_type VARCHAR(255), building_level INT, PRIMARY KEY (building_id));
CREATE TABLE resource_table(resource_id BIGSERIAL NOT NULL, resource_type VARCHAR(255) NOT NULL , kingdom_id BIGINT REFERENCES kingdom_table(kingdom_id), amount INTEGER, PRIMARY KEY (resource_id));
CREATE TABLE troop_table(troop_id BIGSERIAL NOT NULL, kingdom_id BIGINT REFERENCES kingdom_table(kingdom_id), troop_level INTEGER, hp INTEGER, PRIMARY KEY (troop_id));
CREATE TABLE timed_event_table(timed_event_id BIGSERIAL, building_id BIGINT REFERENCES building_table(building_id), was_executed BIT, execution_time BIGINT, PRIMARY KEY (timed_event_id));
INSERT INTO APPUSER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE, POINTS) VALUES
  (1, 'admin', '$2a$08$lDnHPz7eUkSi6ao14Twuau08mzhWrL4kyZGGU5xfiGALO/Vxd5DOi', 'admin', 'admin', 'admin@admin.com',
   TRUE, current_date, 0);
INSERT INTO APPUSER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE, POINTS) VALUES
  (2, 'user', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'enabled@user.com', TRUE, current_date, 0);
INSERT INTO APPUSER (ID, USERNAME, PASSWORD, FIRSTNAME, LASTNAME, EMAIL, ENABLED, LASTPASSWORDRESETDATE, POINTS) VALUES
  (3, 'disabled', '$2a$08$UkVvwpULis18S19S5pZFn.YHPZt3oaqHZnDwqbCW9pft6uFtkXKDC', 'user', 'user', 'disabled@user.com', FALSE, current_date, 0);
INSERT INTO AUTHORITY (ID, NAME) VALUES (1, 'ROLE_USER');
INSERT INTO AUTHORITY (ID, NAME) VALUES (2, 'ROLE_ADMIN');
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (1, 2);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (2, 1);
INSERT INTO USER_AUTHORITY (USER_ID, AUTHORITY_ID) VALUES (3, 1);